apiVersion: v1
entries:
  calert:
  - apiVersion: v2
    appVersion: 99.99.99
    created: "2023-03-24T23:56:48.571899257Z"
    description: A Helm chart for the calert which uses Alertmanager webhook receiver
      to receive alerts payload, and pushes this data to Google Chat webhook endpoint.
    digest: 2e494393fc5f1391da9ff07d7b5f89b1f119f4550aa80ca4cd24d161cb4ba8b3
    home: https://github.com/mr-karan/calert
    keywords:
    - monitoring
    - alerting
    - prometheus
    - alertmanager
    - alertmanager-webhook
    - google-chat
    maintainers:
    - email: hello@mrkaran.dev
      name: Karan Sharma
      url: https://github.com/mr-karan
    name: calert
    sources:
    - https://github.com/mr-karan/calert
    type: application
    urls:
    - https://aslafy-z.github.io/calert/charts/calert-99.99.99.tgz
    version: 99.99.99
generated: "2023-03-24T23:56:48.570968984Z"
