on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Target tag version'  
  push:

jobs:
  chart-releaser:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Helm chart
        uses: stefanprodan/helm-gh-pages@v1.7.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: contrib/helm
          branch: gh-pages
          target_dir: charts
          app_version: ${{ github.event.inputs.tag || '99.99.99' }}
          chart_version: ${{ github.event.inputs.tag || '99.99.99' }}
